Sistema_Encomienda/C1_Presentacion/Controllers/EnvioEncomiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using C3_Dominio.Entidades;
using C3_Dominio.Contratos;
using C2_Aplicacion.Procesos;
using C2_Aplicacion.Mantenimientos;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace C1_Presentacion.Controllers
{
    public class EnvioEncomiendaController : Controller
    {
        GestionarCliente objGestionarCliente = new GestionarCliente();
        EnvioEncomiendaServicio objEnvioEncomienda = new EnvioEncomiendaServicio();
        GestionarRuta objGestionaRuta = new GestionarRuta();
        DetalleDocumentoEnvioEncomienda objDetalleEnvio = new DetalleDocumentoEnvioEncomienda();
        //private double calcularPrecio;
        //private static double subtotal;
        //private static double descuento;
        //private static double montoTotal;
        //private static int idSucursal;

        //SESSION -- VISTAS PARCIALES
        #region Sesion/VistaParciales
        private void CrearTipoDocumentoenSesion()
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("NombreTipo", Type.GetType("System.String"));
            dt.Columns.Add("NumSerie", Type.GetType("System.String"));
            dt.Columns.Add("NumDocumento", Type.GetType("System.String"));
            Session["TipoDocumento"] = dt;
        }
        public ActionResult TipoDocumento(String TipoDocumento)
        {
            if (Session["TipoDocumento"] == null) { CrearTipoDocumentoenSesion(); }
            DataTable dt = (DataTable)Session["TipoDocumento"];
            DocumentoPago documento = objEnvioEncomienda.ObtenerNumeros(TipoDocumento, /*idSucursal*/1);
            Boolean YaExiste = false;
            DataRow r = dt.NewRow();
            foreach (DataRow filas in dt.Rows)
            {
                if (dt.Rows.Count > 0)
                {
                    YaExiste = true;
                    break;
                }
            }
            if (YaExiste && TipoDocumento == "--Seleccionar--")
            {
                Session.Remove("TipoDocumento");
                if (Session["TipoDocumento"] == null) { CrearTipoDocumentoenSesion(); }
                DocumentoPago documento2 = objEnvioEncomienda.ObtenerNumeros(TipoDocumento, /*idSucursal*/1);
                DataRow r2 = dt.NewRow();
                r2["NombreTipo"] = TipoDocumento;
                r2["NumSerie"] = "000";
                r2["NumDocumento"] = "0000000";
                dt.Rows.Add(r2);
                return PartialView();
            }
            else if (YaExiste)
            {
                Session.Remove("TipoDocumento");
                if (Session["TipoDocumento"] == null) { CrearTipoDocumentoenSesion(); }
                DocumentoPago documento2 = objEnvioEncomienda.ObtenerNumeros(TipoDocumento, /*idSucursal*/1);
                DataRow r2 = dt.NewRow();
                r2["NombreTipo"] = TipoDocumento + " DE ENVÍO";
                r2["NumSerie"] = documento2.NumSerie;
                r2["NumDocumento"] = documento2.NumDocumento;
                dt.Rows.Add(r2);

                return PartialView();
            }
            else if (!YaExiste && TipoDocumento == "--Seleccionar--")
            {
                Session.Remove("TipoDocumento");
                if (Session["TipoDocumento"] == null) { CrearTipoDocumentoenSesion(); }
                DocumentoPago documento2 = objEnvioEncomienda.ObtenerNumeros(TipoDocumento, /*idSucursal*/1);
                DataRow r2 = dt.NewRow();
                r2["NombreTipo"] = TipoDocumento;
                r2["NumSerie"] = "000";
                r2["NumDocumento"] = "0000000";
                dt.Rows.Add(r2);
                return PartialView();
            }
            else
            {

                r["NombreTipo"] = TipoDocumento + " DE ENVÍO";
                r["NumSerie"] = documento.NumSerie;
                r["NumDocumento"] = documento.NumDocumento;
                dt.Rows.Add(r); //Session.Remove("TipoDocumento");
                return PartialView();
            }
        }


        private void CrearDetalleEnvioenSesion()
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("Descripcion", Type.GetType("System.String"));
            dt.Columns.Add("Peso", Type.GetType("System.Int32"));
            dt.Columns.Add("CostoGramo", Type.GetType("System.Double"));
            dt.Columns.Add("Precio", Type.GetType("System.Double"));
            Session["DetEnvio"] = dt;
        }

        public ActionResult DetalleEnvio(String Descripcion, Int32 Peso, Int32 idRuta)
        {
            if (Session["DetEnvio"] == null) { CrearDetalleEnvioenSesion(); }
            DataTable dt = (DataTable)Session["DetEnvio"];
            Tarifa tarifa = objGestionaRuta.listarTarifaIdRuta(idRuta);
            Boolean YaExiste = false;
            //   subtotal = 0;
            //if (Session["DetEnvio"] == null) { CrearDetalleEnvioenSesion(); }
            //DataTable dt = (DataTable)Session["DetEnvio"];
            //dt.Rows().Delete();
            //return View();
            foreach (DataRow filas in dt.Rows)
            {
                if (Descripcion == Convert.ToString(filas["Descripcion"]))
                {
                    YaExiste = true;
                    break;
                }
            }
            if (!YaExiste)
            {
                //DataRow r = dt.NewRow();
                //objDetalleEnvio.Peso = Peso;
                //objDetalleEnvio.PrecioGramo = tarifa.PrecioGramo;
                //calcularPrecio = objDetalleEnvio.CalcularPrecio();
                //r["Descripcion"] = Descripcion;
                //r["Peso"] = Peso;
                //r["CostoGramo"] = tarifa.PrecioGramo;
                //r["Precio"] = calcularPrecio;
                //subtotal = objDetalleEnvio.CalcularTotal();
                //  dt.Rows.Add(r);
                return PartialView();
            }
            else
            {
                return PartialView();
                // return RedirectToAction("GestionarEnvioEncomienda", "EnvioEncomienda", new { mensaje = "El producto ingresado Ya Existe" });
            }
        }
        private void BuscarClienteEnvioSesion()
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("IdCliente", Type.GetType("System.Int32"));
            dt.Columns.Add("Nombre", Type.GetType("System.String"));
            dt.Columns.Add("RazonSocial", Type.GetType("System.String"));
            dt.Columns.Add("TipoDocumento", Type.GetType("System.String"));
            Session["ClienteEnvio"] = dt;
        }
        public ActionResult ClienteEnvio(String Remitente)
        {
            if (Session["ClienteEnvio"] == null) { BuscarClienteEnvioSesion(); }
            DataTable dt = (DataTable)Session["ClienteEnvio"];
            Cliente cliente = objGestionarCliente.buscarClientePorNumDocumento2(Remitente);
            Boolean YaExiste = false;
            DataRow r = dt.NewRow();
            foreach (DataRow filas in dt.Rows)
            {
                if (dt.Rows.Count > 0)
                {
                    YaExiste = true;
                    break;
                }
            }
            if (!YaExiste)
            {
                if (cliente != null)
                {
                    r["IdCliente"] = cliente.IdCliente;
                    r["Nombre"] = cliente.NombreCliente + " " + cliente.ApellidoPaternoCliente + " " + cliente.ApellidoMaternoCliente + cliente.RazonSocial;
                    r["RazonSocial"] = cliente.RazonSocial;
                    r["TipoDocumento"] = cliente.TipoDocumento;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else
                {
                    r["IdCliente"] = 0;
                    r["Nombre"] = "--NO REGISTRADO--";
                    r["RazonSocial"] = "";
                    r["TipoDocumento"] = "";
                    dt.Rows.Add(r);
                    return PartialView();
                }
            }
            else
            {
                Session.Remove("ClienteEnvio");
                if (Session["ClienteEnvio"] == null) { BuscarClienteEnvioSesion(); }
                Cliente cliente2 = objGestionarCliente.buscarClientePorNumDocumento2(Remitente);
                if (cliente != null)
                {
                    r["IdCliente"] = cliente2.IdCliente;
                    r["Nombre"] = cliente2.NombreCliente + " " + cliente2.ApellidoPaternoCliente + " " + cliente2.ApellidoMaternoCliente + cliente2.RazonSocial;
                    r["RazonSocial"] = cliente2.RazonSocial;
                    r["TipoDocumento"] = cliente2.TipoDocumento;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else
                {
                    r["IdCliente"] = 0;
                    r["Nombre"] = "--NO REGISTRADO--";
                    r["RazonSocial"] = "";
                    r["TipoDocumento"] = "";
                    dt.Rows.Add(r);
                    return PartialView();
                }
            }
        }
        private void BuscarClienteEntregaSesion()
        {
            DataTable dt = new DataTable();

            dt.Columns.Add("IdCliente", Type.GetType("System.Int32"));
            dt.Columns.Add("Nombre", Type.GetType("System.String"));
            dt.Columns.Add("Direccion", Type.GetType("System.String"));
            dt.Columns.Add("TipoDocumento", Type.GetType("System.String"));
            Session["ClienteEntrega"] = dt;
        }
        public ActionResult ClienteEntrega(String Destinatario)
        {
            if (Session["ClienteEntrega"] == null) { BuscarClienteEntregaSesion(); }
            DataTable dt = (DataTable)Session["ClienteEntrega"];
            DataRow r = dt.NewRow();

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/CalculoPrecios.cshtml
@using System.Data
@{
    DataTable dt = (DataTable)Session["CalcularPrecios"];
    foreach (DataRow r in dt.Rows)
    {
        <div class="form-group row">
            <label class="col-md-2">SubTotal :</label>
            <div class="col-md-3">
                <input name="txtSubTotal" class="form-control" type="text" maxlength="25" id="txtSubTotal" disabled="disabled" value="@r["Total"]" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-2">Descuento :</label>
            <div class="col-md-3">
                <input name="txtDescuento" class="form-control" type="text" maxlength="25" id="txtDescuento" disabled="disabled" value="@r["Descuento"]" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-2">Monto a Pagar :</label>
            <div class="col-md-3">
                <input name="txtMontoPagar" class="form-control" type="text" maxlength="25" id="txtMontoPagar" disabled="disabled" value="@r["MontoTotal"]" />
            </div>
        </div>
    }
}
        <div class="form-group row"><input type="submit" class="btn col-md-3" value="REGISTRAR ENVIO" name="btnRegistrarEnvio" /> </div>

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/ClienteEntrega.cshtml
@using System.Data
@model C3_Dominio.Entidades.Cliente
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
@{
    DataTable dt = (DataTable)Session["ClienteEntrega"];
    foreach (DataRow r in dt.Rows)
    {
        <div class="form-group row">
            <label class="col-md-3">Nombre / Razon Social :</label>
            <div class="col-md-6">
                <input class="form-control" name="txtNombreCliente" type="text" maxlength="25" id="txtNombreCliente" disabled="disabled" value="@r["Nombre"]" />
            </div>
            <form class="col-md-2" action="~/Cliente/NuevoCliente" method="get">
                <input class="btn" type="submit" value="NUEVO CLIENTE" name="btnNuevo" id="btnNuevo" />

            </form>
        </div>
        <div class="editor-label " style="display:none">
            <input name="txtIdClienteEntrega" type="text" maxlength="3" id="txtIdClienteEntrega" style='visibility:hidden' value="@r["IdCliente"]" />
        </div>

    }
}

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/ClienteEnvio.cshtml
@using System.Data
@model C3_Dominio.Entidades.Cliente
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
@{
    DataTable dt = (DataTable)Session["ClienteEnvio"];
    foreach (DataRow r in dt.Rows)
    {
        <div class="form-group row">
            <label class="col-md-3">
                Nombre / Razon Social :
            </label>
            <div class="col-md-6">
                <input class="form-control"  name="txtNombreCliente" type="text" maxlength="25" id="txtNombreCliente" disabled="disabled" value="@r["Nombre"]" />
            </div>
            <form class="col-md-2"  action="~/Cliente/NuevoCliente" method="get">
                <input class="btn"  type="submit" value="NUEVO CLIENTE" name="btnNuevo" id="btnNuevo" />

            </form>
        </div>
        <div class="editor-label " style="display:none">
            <input name="txtIdClienteEnvio" type="text" maxlength="3" id="txtIdClienteEnvio" style='visibility:hidden' value="@r["IdCliente"]" />
        </div>


    }
}

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/DetalleEnvio.cshtml
@using System.Data

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Paquetes a Enviar
            </header>
            <div class="table-responsive">
                <table class="table" id="tbl_Details">
                    <thead>
                    <th>N°</th>
                    <th>Descripcion</th>
                    <th>Peso</th>
                    <th>Precio por Gramo</th>
                    <th>Total</th>
                    </thead>
                    <tbody>
                        @{
                            DataTable dt = (DataTable)Session["DetEnvio"]; int i = 0;
                            foreach (DataRow r in dt.Rows)
                            {
                                i++;
                                <tr>
                                    <td>@i</td>
                                    <td>@r["Descripcion"]</td>
                                    <td>@r["Peso"]</td>
                                    <td>@r["CostoGramo"]</td>
                                    <td>@r["Precio"]</td>
                                    @*<td>
                                       <form action="../EnvioEncomienda/BorrarItem">
                                            <input type="submit" value="Quitar" name="btnBorrar" id="btnBorrar"/>
                                          </form>
                                    </td>*@
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </div>

        </section>
    </div>
</div>
<div id="Borrar">
</div>
<input class="btn" type="button" value="CALCULAR" id="CalculoPrecios" />
<div id="CalcPrecios">
</div>
<script type="text/javascript">
    $("#CalculoPrecios").click(function () {
        $("#CalcPrecios").load('@Url.Action("CalculoPrecios", "EnvioEncomienda")', {

        })
    });
    $("#btnBorrar").click(function () {
        $("#Borrar").load('@Url.Action("BorrarItem", "EnvioEncomienda")', {

        })
    });
</script>

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/EnviarEncomienda.cshtml
@model C3_Dominio.Entidades.DocumentoPago
@{
    ViewBag.Title = "EnviarEncomienda";
    Layout = "~/Views/MasterPrincipal.cshtml";
}

<h2>Enviar Encomienda</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    if (ViewBag.Message != null)
    {
        <div style="padding:5px; width:300px;color:red; border:1px solid green">
            @ViewBag.Message
        </div>
    }
    <form method="post" action="EnviarEncomienda" class="col-md-12">
        <h3 align="center" style="color:red">@ViewBag.mensaje</h3>
        <div class="form-group row">
            <label class="col-md-2">Fecha de Envio :</label>
            <div class="col-md-10">
                <input class="form-control" name="txtFechaEnvio" onkeypress="return soloFechas(event)" type="datetime" id="txtFechaEnvio" value="@Html.DisplayFor(model => model.DocumentoEnvio.FechaEnvio)" placeholder="Fecha DD/MM/AAAA" maxlength="10" onkeypress="return soloFechas(event)" onpaste="return false" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-2">Tipo Comprobante:</label>
            <div class="col-md-10">
                <input class="form-control" disabled="disabled" type="text" name="txtTipoComprobante" id="txtTipoComprobante" value="@Html.DisplayFor(model => model.TipoDocumento)" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-md-2">Dirección :</label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="txtDireccion" id="txtDireccion" value="@Html.DisplayFor(model => model.DocumentoEnvio.ADomicilio)" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-2">Conductor :</label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="txtConductor" id="txtConductor" value="@Html.DisplayFor(model => model.DocumentoEnvio.Conductor)" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-2">Cantidad de paquetes :</label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="txtqtypackages" onkeypress="return solonumeros(event)" id="txtqtypackages" value="@Html.DisplayFor(model => model.DocumentoEnvio.CantidadPaquetes)" />
            </div>
        </div>
        <input type="text" id="txtCantidadPaquetes" style="display:none" value="@Html.DisplayFor(model => model.DocumentoEnvio.CantidadPaquetes2)" />
        <div class="form-group row">
            <input type="submit" class="btn col-md-3" value="REGISTRAR ENVIO" name="EnviarEncomienda" id="EnviarEncomienda" />
        </div>
    </form>
}
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#txtFechaEnvio").datepicker({ dateFormat: 'dd/mm/yy' }).val();
    });
    $("#EnviarEncomienda").click(function (e) {
        if ($("#txtCantidadPaquetes").val() == $("#txtqtypackages").val()) {

        } else {
            e.preventDefault();
            alert("La cantidad no es la misma que se ingresó al gestionar el envío.");
        }
    });
    function solonumeros(e) {
        key = e.keyCode || e.which;
        teclado = String.fromCharCode(key);
        numero = "0123456789";
        especiales = "8-37-38-46";//array
        teclado_especial = false;
        for (var i in especiales) {
            if (key == especiales[i]) {
                teclado_especial = true;
            }
        }
        if (numero.indexOf(teclado) == -1 && !teclado_especial) {
            return false;
        }

    }
    function soloFechas(e) {
        key = e.keyCode || e.which;
        teclado = String.fromCharCode(key);
        numero = "0123456789/";
        especiales = "8-37-38-46";//array
        teclado_especial = false;
        for (var i in especiales) {
            if (key == especiales[i]) {
                teclado_especial = true;
            }
        }
        if (numero.indexOf(teclado) == -1 && !teclado_especial) {
            return false;
        }

    }
</script>

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/GuardarEnvioEncomienda.cshtml
@{
    ViewBag.Title = "GuardarEnvioEncomienda";
    Layout = "~/Views/MasterPrincipal.cshtml";
}

<h2>GuardarEnvioEncomienda</h2>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/ListarEnvios.cshtml
@using System.Data
@{
    ViewBag.Title = "ListarEnvios";
    Layout = "~/Views/MasterPrincipal.cshtml";
}
@model IEnumerable<C3_Dominio.Entidades.DocumentoPago>
<h2>Listar Envíos Pendientes</h2>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Lista de envíos pendientes
            </header>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <th>N°</th>
                    <th>Ruta</th>
                    <th>Tipo Documento</th>
                    <th>FechaEnvio</th>
                    <th>Numero Serie</th>
                    <th>Numero Documento</th>
                    <th>Remitente</th>
                    <th>Destinatario</th>
                    <th>Total</th>
                    <th>Estado</th>
                    <th>Acción</th>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                            if (Model != null)
                            {
                                foreach (var m in Model)
                                {
                                    i++;
                        <tr>
                            <td>@i</td>
                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.Ruta.Descripcion)</td>
                            <td>@Html.DisplayFor(modelItem => m.TipoDocumento)</td>
                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.FechaEnvio)</td>
                            <td>@Html.DisplayFor(modelItem => m.NumSerie)</td>
                            <td>@Html.DisplayFor(modelItem => m.NumDocumento)</td>
                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEnvio.NombreCliente)</td>
                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.NombreCliente)</td>
                            <td>@Html.DisplayFor(modelItem => m.Monto)</td>
                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.Estado)</td>
                            <td>@Html.ActionLink("Enviar", "EnviarEncomienda", new { idEnvio = m.DocumentoEnvio.IdDocumentoEnvioEncomienda })</td>
                        </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>

        </section>
    </div>
</div>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>

Sistema_Encomienda/C1_Presentacion/Views/EnvioEncomienda/TipoDocumento.cshtml
@using System.Data
@model C3_Dominio.Entidades.DocumentoPago
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
@{
    DataTable dt = (DataTable)Session["TipoDocumento"];

    foreach (DataRow r in dt.Rows)
    {
        if (dt.Rows.Count > 0)
        {
            <div class="form-group row">
                <div class="col-md-2">
                    <label name="txtTipoDocumento" id="txtTipoDocumento">
                        @r["NombreTipo"]
                    </label>
                </div>
                <label class="col-md-2">Numero Serie: </label>
                <div class="col-md-3">
                    <input name="txtNSeries" class="form-control" type="text" id="txtNSeries" disabled="disabled" value="@r["NumSerie"]" />
                </div>
                <label class="col-md-2">Numero Documento: </label>
                <div class="col-md-3">
                    <input name="txtNdocumentos" class="form-control" type="text" id="txtNdocumentos" disabled="disabled" value="@r["NumDocumento"]" />
                </div>
                <div class="col-md-3">
                    <input name="txtNSerie" class="form-control" type="text" id="txtNSerie" style='visibility:hidden' value="@r["NumSerie"]" />
                </div>
                <div class="col-md-3">
                    <input name="txtNdocumento" class="form-control" type="text" id="txtNdocumento" style='visibility:hidden' value="@r["NumDocumento"]" />
                </div>

            </div>
        }
    }
}