Sistema_Encomienda/C1_Presentacion/Controllers/ReporteEncomiendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using C3_Dominio.Entidades;
using C3_Dominio.Contratos;
using C2_Aplicacion.Procesos;
using C2_Aplicacion.Mantenimientos;
using System.Data;
namespace C1_Presentacion.Controllers
{
    public class ReporteEncomiendasController : Controller
    {
        EnvioEncomiendaServicio objEnvioEncomienda = new EnvioEncomiendaServicio();
        GestionarCliente objCliente = new GestionarCliente();
        GestionarRuta objRuta = new GestionarRuta();

        public ActionResult ListarReporte()
        {
            //List<Ruta> lstRuta = objRuta.listarRuta();
            //var lsRuta = new SelectList(lstRuta, "idRuta", "Descripcion");
            //ViewBag.ListaRutas = lsRuta;
            return View();
        }

        //    [HttpPost]
          public ActionResult ListarEnvios(String Desde, String Hasta)
        {
            Usuario usuario = (Usuario)Session["usuario"];
            Int32 idSucursal = usuario.sucursal.IdSucursal;
            if (Hasta != "" && Desde != "")
            {
                if (Convert.ToDateTime(Hasta) < Convert.ToDateTime(Desde))
                {
                    ViewBag.mensaje = "Ingrese las fechas Correctas ";
                    return View();
                }

                else
                {
                    List<DocumentoPago> lista = objEnvioEncomienda.ListarReporte(Desde, Hasta, idSucursal);

                    if (lista.Count() > 0)
                    {
                        Session.Remove("MontoTotales");
                        return PartialView(lista);
                    }
                    else
                    {
                        Session.Remove("MontoTotales");
                        ViewBag.mensaje = "No se encontraron envios en ese rango de fechas.";
                        return View();
                    }
                }
            }
            else
            {
                List<DocumentoPago> lista = objEnvioEncomienda.ListarReporte(Desde, Hasta, idSucursal);

                if (lista.Count() > 0)
                {
                    Session.Remove("MontoTotales");
                    return PartialView(lista);
                }
                else
                {
                    Session.Remove("MontoTotales");
                    ViewBag.mensaje = "No se encontraron envios en ese rango de fechas.";
                    return View();
                }
            }
        }


        private void MontoTotalSesion()
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("Monto", Type.GetType("System.Double"));
            Session["MontoTotales"] = dt;
        }

        public ActionResult ObtenerMontoTotal(String Desde, String Hasta)
        {
            Usuario usuario = (Usuario)Session["usuario"];
            Int32 idSucursal = usuario.sucursal.IdSucursal;
            if (Session["MontoTotales"] == null) { MontoTotalSesion(); }
            DataTable dt = (DataTable)Session["MontoTotales"];
            DocumentoPago documento = objEnvioEncomienda.MontoTotalReporte(Desde, Hasta, idSucursal);
            Boolean YaExiste = false; DataRow r = dt.NewRow();
            foreach (DataRow filas in dt.Rows)
            {
                if (dt.Rows.Count > 0)
                {
                    YaExiste = true;
                    break;
                }
            }
            if (!YaExiste)
            {
                if (documento != null)
                {
                    r["Monto"] = documento.Monto;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else
                {
                    ViewBag.mensaje = "Ingrese las fechas Correctas."; return PartialView();
                }
            }
            else
            {
                Session.Remove("MontoTotales");
                if (Session["MontoTotales"] == null) { MontoTotalSesion(); }
                DocumentoPago documento2 = objEnvioEncomienda.MontoTotalReporte(Desde, Hasta,idSucursal);
                if (documento != null)
                {
                    r["Monto"] = documento2.Monto;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else
                {
                    ViewBag.mensaje = "Ingrese las fechas Correctas.";
                    return PartialView();
                }
            }
        }
	}
}

Sistema_Encomienda/C1_Presentacion/Views/ReporteEncomiendas/ListarEnvios.cshtml
@using System.Data
@model IEnumerable<C3_Dominio.Entidades.DocumentoPago>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Lista de Envios por Rango Fechas
            </header>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <th>N°</th>
                    <th>Ruta</th>
                    <th>Tipo Documento</th>
                    <th>FechaEnvio</th>
                    <th>Numero Serie</th>
                    <th>Numero Documento</th>
                    <th>Remitente</th>
                    <th>Destinatario</th>
                    <th>Total</th>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                            if (Model != null)
                            {
                                foreach (var m in Model)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.Ruta.Descripcion)</td>
                                        <td>@Html.DisplayFor(modelItem => m.TipoDocumento)</td>
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.FechaEnvio)</td>
                                        <td>@Html.DisplayFor(modelItem => m.NumSerie)</td>
                                        <td>@Html.DisplayFor(modelItem => m.NumDocumento)</td>
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEnvio.NombreCliente)</td>
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.NombreCliente)</td>
                                        <td>@Html.DisplayFor(modelItem => m.Monto)</td>
                                       
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>

        </section>
    </div>
</div>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>

Sistema_Encomienda/C1_Presentacion/Views/ReporteEncomiendas/ListarReporte.cshtml
@model IEnumerable<C3_Dominio.Entidades.DocumentoPago>

@{
    ViewBag.Title = "ListarReporte";
    Layout = "~/Views/MasterPrincipal.cshtml";
}
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
<h2>ListarReporte</h2>
<form method="post">
    @*Mostrar Por Fecha y Ruta: <input type="radio" name="rbuton" value="fechasRutas" id="fechasRutas">
   Mostrar Por Fechas: <input type="radio" name="rbuton" value="fechas" id="fechas"> 
   Mostrar Por Rutas: <input type="radio" name="rbuton" value="rutas" id="rutas"> 
    </br>
    </br>*@
    <label id="lblDesde">Desde</label><input type="text" name="txtDesde" id="txtDesde" placeholder="Fecha DD/MM/AAAA"  onkeypress="return soloFechas(event)" onpaste="return false" maxlength="10" />
    <label id="lblHasta">Hasta</label><input type="text" name="txtHasta" id="txtHasta" placeholder="Fecha DD/MM/AAAA" onkeypress="return soloFechas(event)" onpaste="return false" maxlength="10" />
   @*<label id="lblRuta">Ruta</label>@Html.DropDownList("Ruta", (SelectList)ViewBag.ListaRutas, "<<Seleccionar>>", new { id = "cboRuta" })*@
    
    <input type="button" id="VerReporte" value="VER REPORTE" />
    <br />
    <div id="bListar">
        <br />

    </div>

    <div id="bCalcula">
        <br />

    </div>
</form>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>
<script type="text/javascript">
    //$(document).ready(function () {
    //    $("#fechasRutas").click(function () {
    //        if ($("#fechasRutas").is(':checked')) {
    //            $("#txtDesde").show("slow");
    //            $("#txtHasta").show("slow");
    //            $("#cboRuta").show("slow");
    //            $("#lblDesde").show("slow");
    //            $("#lblHasta").show("slow");
    //            $("#lblRuta").show("slow");
    //        }

    //    });
    //});
    //$(document).ready(function () {
    //    $("#fechas").click(function () {
    //        if ($("#fechas").is(':checked')) {
    //            $("#txtDesde").show("slow");
    //            $("#txtHasta").show("slow");
    //            $("#cboRuta").hide("slow");
    //            $("#lblRuta").hide("slow");
    //            $("#lblDesde").show("slow");
    //            $("#lblHasta").show("slow");
    //            $("#cboRuta").val("<<Seleccionar>>");
    //        }
         
    //    });
    //});
    //$(document).ready(function () {
    //    $("#rutas").click(function () {
    //        if ($("#rutas").is(':checked')) {
    //            $("#lblRuta").show("slow");
    //            $("#cboRuta").show("slow");
    //            $("#txtDesde").hide("slow");
    //            $("#txtHasta").hide("slow");
    //            $("#lblDesde").hide("slow");
    //            $("#lblHasta").hide("slow");
    //        }
       
    //    });
    //});
    $("#VerReporte").click(function () {
        $("#bListar").load('@Url.Action("ListarEnvios", "ReporteEncomiendas")', {
            Desde: $('#txtDesde').val(), Hasta: $('#txtHasta').val(), idRuta: $('#cboRuta').val()
        })
    });
    $("#VerReporte").click(function () {
        $("#bCalcula").load('@Url.Action("ObtenerMontoTotal", "ReporteEncomiendas")', {
            Desde: $('#txtDesde').val(), Hasta: $('#txtHasta').val(), idRuta: $('#cboRuta').val()
        })
    });


        $(document).ready(function () {
            $("#txtDesde").datepicker({ dateFormat: 'dd/mm/yy' }).val();
            $("#txtHasta").datepicker({ dateFormat: 'dd/mm/yy' }).val();
        });
        function soloFechas(e) {
            key = e.keyCode || e.which;
            teclado = String.fromCharCode(key);
            numero = "0123456789/";
            especiales = "8-37-38-46";//array
            teclado_especial = false;
            for (var i in especiales) {
                if (key == especiales[i]) {
                    teclado_especial = true;
                }
            }
            if (numero.indexOf(teclado) == -1 && !teclado_especial) {
                return false;
            }

        }
</script>

Sistema_Encomienda/C1_Presentacion/Views/ReporteEncomiendas/ObtenerMontoTotal.cshtml
@using System.Data
@model C3_Dominio.Entidades.DocumentoPago
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
@{
    DataTable dt = (DataTable)Session["MontoTotales"];

   foreach (DataRow r  in dt.Rows)
    {
        <table>
            <tr>
                <td>Monto Total de Ingresos:</td>
                <td>
                    <input name="txtMontoTotal" type="text" maxlength="25" id="txtMontoTotal" disabled="disabled" value="@r["Monto"]"/>
                </td>
            </tr>
        </table>
}}
  <h3 align="center" style="color:red">@ViewBag.mensaje</h3>