Sistema_Encomienda/C1_Presentacion/Controllers/RecepcionEncomiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using C3_Dominio.Entidades;
using C3_Dominio.Contratos;
using C2_Aplicacion.Procesos;
using C2_Aplicacion.Mantenimientos;
using System.Data;

namespace C1_Presentacion.Controllers
{
    public class RecepcionEncomiendaController : Controller
    {
        EnvioEncomiendaServicio objEnvioEncomienda = new EnvioEncomiendaServicio();
        GestionarCliente objCliente = new GestionarCliente();
        private static int idSucursal;
        public ActionResult GestionarRecepcionEncomienda()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GestionarRecepcionEncomienda(FormCollection frm)
        {
            idSucursal = Convert.ToInt32(frm["txtIdSucursal"]);
            Int32 idCliente = Convert.ToInt32(frm["txtIdClienteEntrega"]);
            Boolean inserto = objEnvioEncomienda.insertarRecepcionEncomienda(idCliente);

            if (inserto)
            {
                ViewBag.mensaje = "Se Registro la Entrega de la Encomienda";
                return View();
            }
            else
            {
                // ViewBag.mensaje = "No se pudo Registrar la Entrega de la Encomienda";
                return View();
            }

        }
        private void BuscarClienteEntregaSesion()
        {
            DataTable dt = new DataTable();

            dt.Columns.Add("IdCliente", Type.GetType("System.Int32"));
            dt.Columns.Add("Nombre", Type.GetType("System.String"));
            dt.Columns.Add("RazonSocial", Type.GetType("System.String"));
            dt.Columns.Add("TipoDocumento", Type.GetType("System.String"));
            dt.Columns.Add("NroDocumento", Type.GetType("System.String"));
            dt.Columns.Add("Direccion", Type.GetType("System.String"));
            dt.Columns.Add("Telefono", Type.GetType("System.String"));
            Session["BuscaClienteEntrega"] = dt;
        }
        public ActionResult ListarEntrega(String Documento)
        {
            if (Documento == "")
            {
                Session.Remove("BuscaClienteEntrega");
                ViewBag.mensaje = "Ingrese Numero de Documento DNI ( 8 ) o RUC ( 11 ) para buscar Cliente";
                return View();
            }
            else if (Documento != "" && (Documento.Length == 8 || Documento.Length == 11))
            {
                List<DetalleDocumentoEnvioEncomienda> lista = objEnvioEncomienda.buscarClienteEntregaPendiente(Documento, idSucursal);
                if (lista.Count() > 0)
                {
                    Session.Remove("BuscaClienteEntrega");
                    return PartialView(lista);
                }
                else
                {
                    Session.Remove("BuscaClienteEntrega");
                    ViewBag.mensaje = "No se encontraron registros de envíos de encomienda para el cliente o no existe.";
                    return View();
                }
            }
            else if (Documento.Length != 8 || Documento.Length != 11)
            {
                Session.Remove("BuscaClienteEntrega");
                ViewBag.mensaje = "Ingrese Numero de Documento DNI ( 8 ) o RUC ( 11 ) para buscar Cliente";
                return View();
            }
            else
            {
                Session.Remove("BuscaClienteEntrega");
                return View();
            }
        }
        public ActionResult BuscaClienteEntrega(String ClienteEntrega)
        {
            if (Session["BuscaClienteEntrega"] == null) { BuscarClienteEntregaSesion(); }
            DataTable dt = (DataTable)Session["BuscaClienteEntrega"];
            Cliente cliente = objCliente.buscarClientePorNumDocumento2(ClienteEntrega);
            Boolean YaExiste = false;
            DataRow r = dt.NewRow();
            foreach (DataRow filas in dt.Rows)
            {
                if (dt.Rows.Count > 0)
                {
                    YaExiste = true;
                    break;
                }
            } if (!YaExiste)
            {
                if (cliente != null)
                {
                    r["IdCliente"] = cliente.IdCliente;
                    r["Nombre"] = cliente.NombreCliente + " " + cliente.ApellidoPaternoCliente + " " + cliente.ApellidoMaternoCliente + cliente.RazonSocial;
                    r["RazonSocial"] = cliente.RazonSocial;
                    r["TipoDocumento"] = cliente.TipoDocumento;
                    r["NroDocumento"] = cliente.NumeroDocumento;
                    r["Direccion"] = cliente.Direccion;
                    r["Telefono"] = cliente.Telefono;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else { return PartialView(); }
            }
            else
            {
                Session.Remove("BuscaClienteEntrega");
                if (Session["BuscaClienteEntrega"] == null) { BuscarClienteEntregaSesion(); }
                Cliente cliente2 = objCliente.buscarClientePorNumDocumento2(ClienteEntrega);
                if (cliente != null)
                {
                    r["IdCliente"] = cliente2.IdCliente;
                    r["Nombre"] = cliente2.NombreCliente + " " + cliente2.ApellidoPaternoCliente + " " + cliente2.ApellidoMaternoCliente + cliente2.RazonSocial;
                    r["RazonSocial"] = cliente2.RazonSocial;
                    r["TipoDocumento"] = cliente2.TipoDocumento;
                    r["NroDocumento"] = cliente2.NumeroDocumento;
                    r["Direccion"] = cliente2.Direccion;
                    r["Telefono"] = cliente2.Telefono;
                    dt.Rows.Add(r);
                    return PartialView();
                }
                else { return PartialView(); }
            }
        }

        //[HttpPost]
        //public ActionResult RegistrarRecepcionEncomienda(FormCollection frm)
        //{
        //    Int32 idCliente = Convert.ToInt32(frm["txtIdClienteEntrega"]);
        //    Boolean inserto = objEnvioEncomienda.insertarRecepcionEncomienda(idCliente);

        //    if (inserto)
        //    {
        //        return RedirectToAction("GestionarRecepcionEncomienda", "RecepcionEncomienda");
        //    }
        //    else
        //    {
        //        return RedirectToAction("GestionarRecepcionEncomienda", "RecepcionEncomienda", new { mensaje = "No se pudo Insertar" });
        //    }

        //}
	}
}

Sistema_Encomienda/C1_Presentacion/Views/RecepcionEncomienda/BuscaClienteEntrega.cshtml
@using System.Data
@model C3_Dominio.Entidades.Cliente
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
@{
    DataTable dt = (DataTable)Session["BuscaClienteEntrega"];
    foreach (DataRow r in dt.Rows)
    {
        <div class="form-group row">
            <label class="col-md-2">Nombre / Razon Social :</label>
            <div class="col-md-8">
                <input name="txtNombreCliente" class="form-control" type="text" maxlength="25" id="txtNombreCliente" disabled="disabled" value="@r["Nombre"]" />
            </div>
        </div>
        <div class="form-group row">
             <label class="col-md-2">@r["TipoDocumento"] :</label>
             <div class="col-md-8">
                <input name="txtNroDocumento" class="form-control" type="text" maxlength="25" id="txtNroDocumento" disabled="disabled" value="@r["NroDocumento"]" />
            </div>
        </div>
        <div class="form-group row">
             <label class="col-md-2">Direccion :</label>
             <div class="col-md-8"><input class="form-control" name="txtDireccion" type="text" id="txtDireccion" disabled="disabled" value="@r["Direccion"]" /></div>

        </div>
        <div class="form-group row">
             <label class="col-md-2">Telefono :</label>
             <div class="col-md-8"><input class="form-control" name="txtTelefono" type="text" id="txtTelefono" disabled="disabled" value="@r["Telefono"]" /></div>

        </div>
        <div class="form-group row">
             <label class="col-md-2">
                <input name="txtIdClienteEntrega" class="form-control" type="text" maxlength="3" id="txtIdClienteEntrega" style='visibility:hidden' value="@r["IdCliente"]" />
            </label>
        </div>

    }
}

Sistema_Encomienda/C1_Presentacion/Views/RecepcionEncomienda/GestionarRecepcionEncomienda.cshtml
@model IEnumerable<C3_Dominio.Entidades.DetalleDocumentoEnvioEncomienda>
@{
    ViewBag.Title = "GestionarRecepcionEncomienda";
    Layout = "~/Views/MasterPrincipal.cshtml";
}
<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>
<h2>Gestionar Recepcion Encomienda</h2>
<form method="post">
    @*action="~/RecepcionEncomienda/RegistrarRecepcionEncomienda"*@
    <div class="form-group row">
        <label class="col-md-2">Cliente Entrega:</label>
        <div class="col-md-8">
            <input type="text" class="form-control" name="txtDniRuc2" id="txtDniRuc2" placeholder="Ingresa RUC o DNI" maxlength="11" onkeypress="return solonumeros(event)" onpaste="return false" />

        </div>  <input type="button" class="col-md-2 btn" value="BUSCAR" id="BuscaClienteEntrega" />
    </div>
    <div id="bEnvio">
        <br />

    </div>
    <div id="bDetalle">
        <br />

    </div>


    <br />

</form>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>
<script type="text/javascript">
    $("#BuscaClienteEntrega").click(function () {
        $("#bEnvio").load('@Url.Action("BuscaClienteEntrega", "RecepcionEncomienda")', {
            ClienteEntrega: $('#txtDniRuc2').val()
        })
    });
    $("#BuscaClienteEntrega").click(function () {
        $("#bDetalle").load('@Url.Action("ListarEntrega", "RecepcionEncomienda")', {
            Documento: $('#txtDniRuc2').val()
        })
    });
    function solonumeros(e) {
        key = e.keyCode || e.which;
        teclado = String.fromCharCode(key);
        numero = "0123456789";
        especiales = "8-37-38-46";//array
        teclado_especial = false;
        for (var i in especiales) {
            if (key == especiales[i]) {
                teclado_especial = true;
            }
        }
        if (numero.indexOf(teclado) == -1 && !teclado_especial) {
            return false;
        }

    }
</script>

Sistema_Encomienda/C1_Presentacion/Views/RecepcionEncomienda/ListarEntrega.cshtml
@using System.Data
@model IEnumerable<C3_Dominio.Entidades.DetalleDocumentoEnvioEncomienda>

<script src="~/Bootstrap/js/jquery-1.11.0.js"></script>


<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Paquetes a Entregar
            </header>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        @*<th>Nro. Documento</th>
                            <th>Razon Social</th>
                            <th>Nombre</th>
                            <th>Ap.Paterno</th>
                            <th>Ap.Materno</th>*@
                    <th>N°</th>
                    <th>Remitente</th>
                    <th>Fecha Envio</th>
                    <th>Descripcion</th>
                    <th>Peso</th>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                            if (Model != null)
                            {
                                foreach (var m in Model)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        @*<td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.NumeroDocumento)</td>
                                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.RazonSocial)</td>
                                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.NombreCliente)</td>
                                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.ApellidoPaternoCliente)</td>
                                            <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.ApellidoMaternoCliente)</td>*@
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEnvio.NombreCliente)</td>
                                        <td>@Html.DisplayFor(modelItem => m.DocumentoEnvio.FechaEnvio)</td>
                                        <td>@Html.DisplayFor(modelItem => m.Descripcion)</td>
                                        <td>@Html.DisplayFor(modelItem => m.Peso)</td>
                                        @* <td><input name="txtId" type="text" maxlength="1" id="txtId" style='visibility:hidden' value="@Html.DisplayFor(modelItem => m.DocumentoEnvio.ClienteEntrega.IdCliente)" /></td>*@
                                    </tr>
                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<h3 align="center" style="color:red">@ViewBag.mensaje</h3>
<table>
    <tr>
        <td><input type="submit" class="btn" value="REGISTRAR ENTREGA" name="btnRegistrar" /></td>
    </tr>
</table>